export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const REQUEST_SEARCH_FAILURE = 'REQUEST_SEARCH_FAILURE';
export const RECEIVE_VIDEOS = 'RECEIVE_VIDEOS';

export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';