export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const REQUEST_SEARCH_SUCCESS = 'REQUEST_SEARCH_SUCCESS';
export const REQUEST_SEARCH_FAILURE = 'REQUEST_SEARCH_FAILURE';
export const RECEIVE_VIDEOS = 'RECEIVE_VIDEOS';