export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const REQUEST_SEARCH_FAILURE = 'REQUEST_SEARCH_FAILURE';
export const RECEIVE_VIDEOS = 'RECEIVE_VIDEOS';

export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';

export const ADD_VIDEO_TO_HISTORY = 'ADD_VIDEO_TO_HISTORY';
export const REMOVE_VIDEO_FROM_HISTORY = 'REMOVE_VIDEO_FROM_HISTORY';

export const TOOGLE_SEARCH_LIST = 'TOOGLE_SEARCH_LIST';